name: Next Stop Is Build Action

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install packages
      run: npm ci
      working-directory: next-stop-is

    - name: Build next stop is
      run: npm run build --if-present
      working-directory: next-stop-is

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: next-stop-is
        start: npm run dev
        browser: chrome

